# Generated by Django 5.2.8 on 2026-09-01 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('plataforma', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('total_capitulos', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo_atual', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Lendo', 'Lendo'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado'), ('Abandonado', 'Abandonado')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leituras.obra')),
            ],
        ),
    ]
