# Generated by Django 5.2.8 on 2026-09-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
