# Generated by Django 5.2.8 on 2026-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0002_alter_obra_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('Fanfic', 'Fanfic'), ('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('Webtoon', 'Webtoon')], default='Fanfic', max_length=20),
        ),
    ]
