# Generated by Django 5.2.8 on 2026-09-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0003_obra_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('Fanfic', 'Fanfic'), ('Manga', 'Mangá'), ('Manhwa', 'Manhwa'), ('Webtoon', 'Webtoon'), ('HQ', 'HQ'), ('Materia', 'Matéria'), ('Light Novel', 'Light Novel')], default='Fanfic', max_length=20),
        ),
    ]
