# Generated by Django 5.2.8 on 2026-09-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0004_alter_obra_link_alter_obra_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='avancado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
