# Generated by Django 5.2.8 on 2026-09-11 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0005_leitura_avancado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obra',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='obra',
            constraint=models.UniqueConstraint(fields=('dono', 'link'), name='link_unico_por_dono'),
        ),
    ]
